name: Build & Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      shell: pwsh
      run: |
        pyinstaller src/main.py `
          --name LANCryptor `
          --onefile `
          --noconsole `
          --distpath dist `
          --workpath build `
          --specpath build

    - name: Clean old ZIP
      run: |
        if (Test-Path LANCryptor-win.zip) { Remove-Item LANCryptor-win.zip }

    - name: Zip EXE
      run: |
        Compress-Archive -Path dist\LANCryptor.exe, README.md, LICENSE -DestinationPath LANCryptor-win.zip

    - name: Create or update GitHub Release and upload asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: LANCryptor-win.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
